trigger:
  - master

pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: acs-ios
  - group: git-credentials
  - group: source-clear-credentials
  - group: ios-signing
  - name: configuration
    value: 'Release'
  - name: sdk
    value: 'iphoneos'
  - name: cocoapods_path
    value: $(Pipeline.Workspace)/.cocoapods

steps:
- checkout: self
  submodules: true

- task: CmdLine@2
  displayName: Adding Alfresco private podspec repository
  inputs:
    script: |
      pod repo add AlfrescoPodspec https://$(gitUser):$(gitPAT)@github.com/Alfresco/alfresco-private-podspecs-ios-sdk.git

- task: Cache@2
  inputs:
    key: 'cocoapods | Podfile.lock'
    restoreKeys: cocoapods
    path: $(cocoapods_path)
  displayName: Cache CocoaPods Specs

- task: Cache@2
  inputs:
    key: 'pods | Podfile.lock'
    restoreKeys: pods
    path: Pods
  displayName: Cache Pods
      
- task: CmdLine@2
  displayName: Installing pods
  inputs:
    script: |
      pod install || pod install --repo-update
  env:
    CP_HOME_DIR: $(cocoapods_path)
- task: ios-bundle-version@1
  inputs:
    sourcePath: 'ContentApp/Supporting Files/Info.plist'
    versionCodeOption: 'buildid'
    versionCode: '$(build_version)'
    versionName: '2.8.1'
    printFile: true

- task: CmdLine@2
  displayName: Variable substitution for GoogleAnalytics
  inputs:
    script: 'plutil -replace API_KEY -string $(GA_API_KEY) GoogleService-Info.plist'
    workingDirectory: '$(System.DefaultWorkingDirectory)/AlfrescoApp/Supporting Files/'

- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true 
  
- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioning_profile)'
   removeProfile: true 

- task: DownloadSecureFile@1
  name: prov_profile
  inputs:
    secureFile: '$(provisioning_profile)'

# - task: Xcode@5
#   displayName: 'Generate Content Services IPA'
#   inputs:
#     actions: 'build'
#     scheme: 'AlfrescoApp'
#     sdk: '$(sdk)'
#     configuration: '$(configuration)'
#     xcWorkspacePath: '**/AlfrescoApp.xcworkspace'
#     xcodeVersion: 'default'
#     packageApp: true
#     signingOption: 'manual'
#     signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
#     provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)' 
    artifactName: 'ACS-iOS' 
    publishLocation: 'Container'

- task: CmdLine@2
  displayName: 'Build and Pilot'
  inputs:
    script: 'bundle update && bundle exec fastlane build_and_pilot'
  env:
      FASTLANE_DISABLE_COLORS: 'true'
      FASTLANE_USER: $(appstore_upload_user)
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: $(appstore_upload_token)
      PROV_PROFILE: $(prov_profile.secureFilePath)
      SIGNING_IDENTITY: $(signing_identity)
      APPSTORE_APP_ID: $(appstore_app_id)
      CONFIGURATION: $(configuration)

- task: CmdLine@2
  inputs:
    script: 'curl -sSL https://download.sourceclear.com/ci.sh | sh'
  displayName: 'Performing Source Clear checks'
  env:
    SRCCLR_API_TOKEN: $(source_clear_token)