trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  - group: cs-ios-signing
  - name: configuration
    value: 'Release'
  - name: sdk
    value: 'iphoneos'

steps:
- checkout: self
  submodules: true

- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true 
  
- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(csReleaseProvisioningProfile)'
   removeProfile: true 

- task: Xcode@5
  inputs:
    actions: 'build archive'
    scheme: 'AlfrescoApp'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/AlfrescoApp.xcworkspace'
    xcodeVersion: 'default'
    packageApp: true
    archivePath: ''$(agent.buildDirectory)'
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.*'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)' 
    artifactName: 'ACS-iOS' 
    publishLocation: 'Container'

- task: CmdLine@2
  inputs:
    script: 'curl -sSL https://download.sourceclear.com/ci.sh | sh'
  displayName: 'Performing Source Clear checks'
  env:
    SRCCLR_API_TOKEN: $(SOURCE_CLEAR_API_TOKEN)